In [299]:
import numpy as np

In [300]:
#criar uma matriz unidimensional 
mt = np.array([12,34,26,18,10]) 
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [301]:
#criar o array com um tipo especifico 
# cria o array como float de 64 bits
mtfloat = np.array([1, 2, 3], dtype = np.float64)  
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1, 2, 3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [302]:
#mudar o tipo de array 
#pode transforma tipo de dados de arrays 
mtnew = np.array([1.4, 3.6, -5,1, 9.42, 4.999999])
print(mtnew)

# quando transforma de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)


[ 1.4       3.6      -5.        1.        9.42      4.999999]
[ 1  3 -5  1  9  4]


In [303]:
# podemos fazer o inverso tbm 
mt5 = np.array([1, 2, 3, 4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [304]:
#mais de uma dimensão 
#Criar uma matriz bidimensional 
mt7 = np.array([[7,2,23], [12,27,4], [5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [305]:
#criar arrays vazios tipificados
#empty significa que não são inicializadas, não que são vazias
vzo = np.empty([3,2], dtype = int)
print(vzo)
print("-------")

[[4608983858650965606 4615288898129284301]
 [4617315517961601024 4607182418800017408]
 [4621492606615987159 4617315516835701117]]
-------


In [306]:
#criar uma matriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)
print("-------")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------


In [307]:
#com valores igual a um 
um = np.zeros([5,7])
print(um)
print("-------")

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
-------


In [308]:
#criar matriz quadrada com diagonal principal com valores 1 e os outros valores zero
diagonal = np.eye(5)
print(diagonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [309]:
#valores aleatorios entre zero e um 
ale = np.random.random((5))
print(ale)
print("-------")

[0.41696995 0.78860758 0.0153496  0.72207436 0.11666965]
-------


In [310]:
#valores aleatórios distr. normal contendo negativos 
ale2 = np.random.rand((5))
print(ale2)
print("-------")

[0.56190819 0.7513807  0.70998441 0.33652274 0.93630203]
-------


In [311]:
#valores aleatorios 4x3
ale3 = (10*np.random.random((3,4)))
print(ale3)

[[5.84977261 6.68287464 0.42653686 5.40022529]
 [4.64580543 1.64168716 2.64219386 6.36825978]
 [6.21133292 8.8223771  0.4404566  2.29120711]]


In [312]:
#outra forma de gerar aleatorio 
#uso de semente

gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)


[0.51182162 0.9504637  0.14415961]


In [313]:
#gerar inteiros
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [314]:
#unique remove repetições 

j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [315]:
#funções especificas
#criar matriz bidimensional 
k = np.array([[17,23,44], [28,24,15], [14,25,33]])
# mostrar a matriz k 
print(k)
# mostrar um elemento especifico de matriz k
print(k[0][1])
#mostra o tamanho das dimensões da matriz k 
print(k.shape)

[[17 23 44]
 [28 24 15]
 [14 25 33]]
23
(3, 3)


In [316]:
#funções matemáticas 
#mostra o maior valor da matriz k
print(k.max())
#mostra o menor valor da matriz k
print(k.min())
#mostra a soma dos valores da matriz k
print((k.sum()))
#mostra o valor da media dos valores da matriz k
print(k.mean())
#mostra o valor do desvio padrão (standard deviation)dos valores matriz k
print(k.std())

44
14
223
24.77777777777778
8.966329334147563


In [317]:
#funções universais, aplicadas a todos os elementos 
# mostrar o valor da raiz quadrada de todos os elementos 

k1 = np.array([1,4,9,16,25,36])
print(np.sqrt(k1))

#mostrar o valor do exponencial de todos elementos 

print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [318]:
#extraçãos de elementos 
m = np.array([1, 2, 3, 4, 5, 6])
#mostra elementos da posição 2
print(m[1])
print("-------")
#mostra o array criado a partir da posição 0, dois elementos
print(m[0:3])
print("-------")
#mostrar o array criado a partir da 2a posição 
# até todo o restante do array 
print(m[2:])
print("-------")
#mostra o array criado a partir da antepenultima
#posição até o final 
print(m[-5:])


2
-------
[1 2 3]
-------
[3 4 5 6]
-------
[2 3 4 5 6]


In [319]:
#extração de linhas e colunas 

l = np.array([[4,5],[6,1], [7,4]])
print(l)
print("-------")

#primeira linha, todas as colunas 
l_linha_1 = l[0, :]
print(l_linha_1)
print("-------")

#segunda linha 
l_linha_2 = l[1, :]
print(l_linha_2)
print("-------")

#terceira linha 
l_linha_3 = l[2, :]
print(l_linha_3)
print("-------")

#todas as linhas, primeiro coluna 
l_coluna_1 = l[:,0]
print(l_coluna_1)
print("-------")

#todas as linhas, segunda coluna 
l_coluna_2 = l[:,1]
print(l_coluna_2)
print("-------")


[[4 5]
 [6 1]
 [7 4]]
-------
[4 5]
-------
[6 1]
-------
[7 4]
-------
[4 6 7]
-------
[5 1 4]
-------


In [320]:
#adição e multiplicação de matriz 
n = np.array([[1,2], [3,4]])
o = np.array([[1,1], [1,1]])
res1 = n+o
print(res1)
print("-------")

res2 = n*o
print(res2)
print("-------")

p = np.array([[1,2], [3,4], [5,6]])
q = np.array([[2,1]])
print(p+q)

[[2 3]
 [4 5]]
-------
[[1 2]
 [3 4]]
-------
[[3 3]
 [5 5]
 [7 7]]


In [321]:
# transposição rearranja um conjunto de 15 elementos de 0 a 14 
# em 3 linhas e 5 colunas 

f = np.arange(15).reshape((3, 5))

#mostrar a matrizes transposta entre linha e coluna
print(f)
print("-------")
s = f.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [322]:
#outra forma de fazer, mesmo resultado
r = np.arange(15).reshape((3, 5))
print(r)
print("-------")

#rearranja um conjunto de 15 elementos
# mostra a matriz transposta entre linha e coluna
s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [323]:
#expressão logicas
#usando where 
#criando matriz com valores aleatorios positivos e negativos 
v = np.random.rand(4, 4)
print(v)
#criando matriz com valores booelanos baseados no array v 
x = (v > 0)
print(x)
#criando matriz com valores -1 e 1 baseados nos valores do array x 
z = np.where(x > 0, 1, -1)
print(z)

[[0.42979602 0.74163091 0.98385706 0.93405387]
 [0.75441778 0.88002957 0.61766228 0.05817897]
 [0.70866181 0.40659082 0.397948   0.1883262 ]
 [0.98826747 0.59179083 0.86289773 0.84477404]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
