In [1]:
import numpy as np

In [2]:
#criar uma matriz unidimensional 
mt = np.array([12,34,26,18,10]) 
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [3]:
#criar o array com um tipo especifico 
# cria o array como float de 64 bits
mtfloat = np.array([1, 2, 3], dtype = np.float64)  
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1, 2, 3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [4]:
#mudar o tipo de array 
#pode transforma tipo de dados de arrays 
mtnew = np.array([1.4, 3.6, -5,1, 9.42, 4.999999])
print(mtnew)

# quando transforma de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)


[ 1.4       3.6      -5.        1.        9.42      4.999999]
[ 1  3 -5  1  9  4]
