In [14]:
import numpy as np

In [15]:
#criar uma matriz unidimensional 
mt = np.array([12,34,26,18,10]) 
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [16]:
#criar o array com um tipo especifico 
# cria o array como float de 64 bits
mtfloat = np.array([1, 2, 3], dtype = np.float64)  
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1, 2, 3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [17]:
#mudar o tipo de array 
#pode transforma tipo de dados de arrays 
mtnew = np.array([1.4, 3.6, -5,1, 9.42, 4.999999])
print(mtnew)

# quando transforma de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)


[ 1.4       3.6      -5.        1.        9.42      4.999999]
[ 1  3 -5  1  9  4]


In [18]:
# podemos fazer o inverso tbm 
mt5 = np.array([1, 2, 3, 4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [19]:
#mais de uma dimensão 
#Criar uma matriz bidimensional 
mt7 = np.array([[7,2,23], [12,27,4], [5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [ ]:
#criar arrays vazios tipificados
#empty significa que não são inicializadas, não que são vazias
vazio = np.empty([3,2],dtype = int)
print(vazio)
print("---------")
#criar uma matriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)
print("---------")
#com valores igual a um 
um = np.zeros([5,7])
print(um)
print("---------")
#criar matriz quadrada com diagonal principal com valores 1 e os outros valores zero
diagonal = np.eye(5)
print(diagonal)