In [174]:
import numpy as np

In [175]:
#criar uma matriz unidimensional 
mt = np.array([12,34,26,18,10]) 
print(mt)
print(type(mt))

[12 34 26 18 10]
<class 'numpy.ndarray'>


In [176]:
#criar o array com um tipo especifico 
# cria o array como float de 64 bits
mtfloat = np.array([1, 2, 3], dtype = np.float64)  
print(mtfloat)
print(type(mtfloat))
mtint = np.array([1, 2, 3], dtype = np.int32)
print(mtint)
print(type(mtint))

[1. 2. 3.]
<class 'numpy.ndarray'>
[1 2 3]
<class 'numpy.ndarray'>


In [177]:
#mudar o tipo de array 
#pode transforma tipo de dados de arrays 
mtnew = np.array([1.4, 3.6, -5,1, 9.42, 4.999999])
print(mtnew)

# quando transforma de float para int os valores são truncados
mtnewint = mtnew.astype(np.int32)
print(mtnewint)


[ 1.4       3.6      -5.        1.        9.42      4.999999]
[ 1  3 -5  1  9  4]


In [178]:
# podemos fazer o inverso tbm 
mt5 = np.array([1, 2, 3, 4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [179]:
#mais de uma dimensão 
#Criar uma matriz bidimensional 
mt7 = np.array([[7,2,23], [12,27,4], [5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [180]:
#criar arrays vazios tipificados
#empty significa que não são inicializadas, não que são vazias
vzo = np.empty([3,2], dtype = int)
print(vzo)
print("-------")

[[4608983858650965606 4615288898129284301]
 [4617315517961601024 4607182418800017408]
 [4621492606615987159 4617315516835701117]]
-------


In [181]:
#criar uma matriz 4x3 com valores zero
zeros = np.zeros([4,3])
print(zeros)
print("-------")

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------


In [182]:
#com valores igual a um 
um = np.zeros([5,7])
print(um)
print("-------")

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
-------


In [183]:
#criar matriz quadrada com diagonal principal com valores 1 e os outros valores zero
diagonal = np.eye(5)
print(diagonal)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [184]:
#valores aleatorios entre zero e um 
ale = np.random.random((5))
print(ale)
print("-------")

[0.94714166 0.15719008 0.9172115  0.77975719 0.60093451]
-------


In [185]:
#valores aleatórios distr. normal contendo negativos 
ale2 = np.random.rand((5))
print(ale2)
print("-------")

[0.27088966 0.64213504 0.6841649  0.77654111 0.62949346]
-------


In [186]:
#valores aleatorios 4x3
ale3 = (10*np.random.random((3,4)))
print(ale3)

[[4.68890276 9.39847766 7.08981268 1.77986991]
 [6.77730774 5.00042397 3.70209161 7.67290761]
 [5.00599123 7.38331965 2.46893874 1.56592292]]


In [187]:
#outra forma de gerar aleatorio 
#uso de semente

gnr = np.random.default_rng(1)
ale5 = gnr.random(3)
print(ale5)


[0.51182162 0.9504637  0.14415961]


In [188]:
#gerar inteiros
ale6 = gnr.integers(10, size=(3,4))
print(ale6)

[[8 9 2 3]
 [8 4 2 8]
 [2 4 6 5]]


In [189]:
#unique remove repetições 

j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [190]:
#funções especificas
#criar matriz bidimensional 
k = np.array([[17,23,44], [28,24,15], [14,25,33]])
# mostrar a matriz k 
print(k)
# mostrar um elemento especifico de matriz k
print(k[0][1])
#mostra o tamanho das dimensões da matriz k 
print(k.shape)

[[17 23 44]
 [28 24 15]
 [14 25 33]]
23
(3, 3)


In [191]:
#funções matemáticas 
#mostra o maior valor da matriz k
print(k.max())
#mostra o menor valor da matriz k
print(k.min())
#mostra a soma dos valores da matriz k
print((k.sum()))
#mostra o valor da media dos valores da matriz k
print(k.mean())
#mostra o valor do desvio padrão (standard deviation)dos valores matriz k
print(k.std())

44
14
223
24.77777777777778
8.966329334147563
